# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the master repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Get the master package versions and hash
        run: |
          if [ -f package.json ]; then
            echo masterPackageVersion="$(jq -r '.version | split(".") | join("") | tonumber' package.json)" >> "$GITHUB_ENV"
          fi
          if [ -f composer.json ]; then
            echo masterComposerVersion="$(jq -r '.version | split(".") | join("") | tonumber' composer.json)" >> "$GITHUB_ENV"
          fi
          if [ -f composer.lock ]; then
            echo masterComposerLockHash="$(jq -r '."content-hash"' composer.lock)" >> "$GITHUB_ENV"
          fi
      - name: Checkout the current repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Compare the current versions with the masters versions
        run: |
          if [ -f package.json ]; then
            packageVersion="$(jq -r '.version | split(".") | join("") | tonumber' package.json)"
            echo "current: $packageVersion master: $masterPackageVersion"
          fi
          if [ -f composer.json ]; then
            composerVersion="$(jq -r '.version | split(".") | join("") | tonumber' composer.json)"
            echo "current: $composerVersion master: $masterComposerVersion"
          fi
          if [ -f composer.lock ]; then
            composerLockHash="$(jq -r '."content-hash"' composer.lock)"
            echo "current: $composerLockHash master: $masterComposerLockHash"
            if [ "$masterComposerLockHash" == "$composerLockHash" ]; then
              exit 1
            fi
          fi
