# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Grab master variables
        run: |
          if [ -f package.json ]; then
            packageVersion="$(jq -r '.version' package.json)"
            echo "$packageVersion"
          fi
          if [ -f composer.json ]; then
            composerVersion="$(jq -r '.version' composer.json)"
            echo "$composerVersion"
          fi
          if [ -f composer.lock ]; then
            composerLockHash="$(jq -r '."content-hash"' composer.lock)"
            echo "$composerLockHash"
          fi
        env:
          MASTER_PACKAGE_VERSION: "$packageVersion"
          MASTER_COMPOSER_VERSION: "$composerVersion"
          MASTER_COMPOSER_HASH: "$composerLockHash"
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Check versions
        run: |
          if [ -f package.json ]; then
            packageVersion="$(jq -r '.version' package.json)"
            echo "$packageVersion master: $MASTER_PACKAGE_VERSION"
          fi
          if [ -f composer.json ]; then
            composerVersion="$(jq -r '.version' composer.json)"
            echo "$composerVersion master: $MASTER_COMPOSER_VERSION"
          fi
          if [ -f composer.lock ]; then
            composerLockHash="$(jq -r '."content-hash"' composer.lock)"
            echo "$composerLockHash master: $MASTER_COMPOSER_HASH"
          fi
