# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps: 
      - name: Check package.json
        run: echo "checking package"
      - name: Check composer.json
        run: echo "$GITHUB_CONTEXT"
