# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout master repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Get Master Variables
        run: |
          if [ -f package.json ]; then
            echo masterPackageVersion="$(jq -r '.version' package.json)" >> "$GITHUB_ENV"
          fi
          if [ -f composer.json ]; then
            echo masterComposerVersion="$(jq -r '.version' composer.json)" >> "$GITHUB_ENV"
          fi
          if [ -f composer.lock ]; then
            echo masterComposerLockHash="$(jq -r '."content-hash"' composer.lock)" >> "$GITHUB_ENV"
          fi
      - name: checkout current repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Check versions
        run: |
          if [ -f package.json ]; then
            packageVersion="$(jq -r '.version' package.json)"
            echo "master: $masterPackageVersion,  $packageVersion" | sed 's/\.//g'
          fi
          if [ -f composer.json ]; then
            composerVersion="$(jq -r '.version' composer.json)"
            echo "master: $masterComposerVersion,  $composerVersion" | sed 's/\.//g'
          fi
          if [ -f composer.lock ]; then
            composerLockHash="$(jq -r '."content-hash"' composer.lock)"
           echo "master: $masterComposerLockHash, $composerLockHash" | sed 's/\.//g'
          fi
