# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master
# MASTER_PACKAGE_VERSION=1.2.3; 
# [[ $(cut -d'.' -f1 <<<$MASTER_PACKAGE_VERSION) -lt $(jq -r '.version' ./package.json | cut -d'.' -f1) ]]
# | split(".") | join("") | tonumber
# test="$(jq -r '.version' ./package.json)"; echo $test
# [[ 5 -lt 3 || 15 -lt 10 || 0 -gt 5 ]] && echo 'hello' || echo 'No' 
# Start with incoming one
jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the master repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Get the master package versions and hash
        run: |
          if [ -f package.json ]; then
            echo MASTER_PACKAGE_VERSION="$(jq '.version' package.json)" >> "$GITHUB_ENV"
          fi
          if [ -f composer.json ]; then
            echo MASTER_COMPOSER_VERSION="$(jq -r '.version' composer.json)" >> "$GITHUB_ENV"
          fi
          if [ -f composer.lock ]; then
            echo MASTER_COMPOSER_LOCK_HASH="$(jq -r '."content-hash"' composer.lock)" >> "$GITHUB_ENV"
          fi
      - name: Checkout the current repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Compare the current versions with the masters versions
        run: |
          if [ -f package.json ]; then
            packageVersion="$(jq -r '.version | split(".") | join("") | tonumber' package.json)"
            if [ $packageVersion <= $masterPackageVersion ]; then 
              exit 0
            fi
          fi
          if [ -f composer.json ]; then
            composerVersion="$(jq -r '.version | split(".") | join("") | tonumber' composer.json)"
            if [ $composerVersion <= $masterComposerVersion ]; then 
              exit 0
            fi
          fi
          if [ -f composer.lock ]; then
            composerLockHash="$(jq -r '."content-hash"' composer.lock)"
            if [ "$masterComposerLockHash" == "$composerLockHash" ]; then
              exit 0
            fi
          fi
