# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Check composer.json
        run: versionFoo="$(jq -r '.version' package.json)" && echo "$versionFoo"
      - name: Check composer-lock.json
        run: echo "Checking composer-lock.json"
