# Check if the versions were updated
# and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  compare-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the master branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: master
      - name: Get master's package, package-lock, and composer versions
        run: |
          version=
            for file in package.json package-lock.json composer.json; do
              if ! [ -f "$file" ]; then
                continue
              fi

              if [ -n "$version" ] && [ "$version" != "$(jq -r '.version' "$file")" ]; then 
                echo "The version in $file does not match with the other versions"
                exit 1
              fi

              version="$(jq -r '.version' "$file")"
            done

            if [ -z "$version" ]; then
              echo 'no versions were found on the master branch'
              exit 1
            fi

            echo MASTER_VERSION="$(version)" >>"$GITHUB_ENV"
      
      - name: Get master's composer.lock hash-content
        run: |
          if [ -f composer.lock ]; then
            echo MASTER_COMPOSER_HASH="$(jq -r '."content-hash"' composer.lock)" >>"$GITHUB_ENV"
          fi
      - name: Checkout the current branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
      - name: Check versions in package, package-lock, and composer
        run: |
          for file in package.json package-lock.json composer.json; do
           
            exit 1
          done
      - name: Check composer.lock's hash
        run: |
          if [ -f composer.lock ]; then
            current_hash="$(jq '."content-hash"' composer.lock)"
            if [ $current_hash != $MASTER_COMPOSER_HASH ]; then 
              exit 0
            fi

            echo "composer.lock's hash needs to be updated"
            exit 1
          fi
          
