# Check if the correct versions were 
# updated and stop the deployment if not
name: check-for-updated-versions

on: 
  pull_request:
    branches:
      - master

jobs:
  check-package-version:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
        run: |
          masterVersions="1.33.0"
      - name: Check versions
        run: |
          if [ -f package.json ]; then
            packageVersion="$(jq -r '.version' package.json)"
            echo "$packageVersion master: $masterVersions"
          fi
          if [ -f composer.json ]; then
            composerVersion="$(jq -r '.version' composer.json)"
            echo "$composerVersion master: $masterVersions"
          fi
          if [ -f composer.lock ]; then
            composerLockHash="$(jq -r '."content-hash"' composer.lock)"
            echo "$composerLockHash master: $masterVersions"
          fi
